### ISSUE TITLE
README should use venv activation

### ISSUE THREAD

**Issue by trickeydan** [sown/backup#2]
Generally it is recommended to use the `activate` script when using a virtualenv

`source venv/bin/activate`

This essentially adds the `venv/bin` to `$PATH` in a new, exitable shell.

Alternatively, I would recommend using a proper dependency manager like [Poetry](https://python-poetry.org).

**Comment by TimStallard** [comment]
I'm not particularly keen on changing the pip install section, as running system-wide pip by accident could end quite badly. I'll update the flake8 one however, as that'd normally be run regularly during development so you probably want to have the venv activated then anyway.

**Comment by trickeydan** [comment]
Perhaps we should consider packaging this as a deb?

Sidenote: It's generally considered best to wait until everyone on an issue is in agreement before closing it. I've seen not doing this cause conflict on other projects.

**Comment by TimStallard** [comment]
Considering this is only planned to be installed on the two backup servers, I'm not convinced it's worthwhile packaging it, particularly as it would be a bunch of effort building a proper repo and maintaining the dependencies?

If we end up writing python stuff that we deploy to all servers though, I think properly packaging that would be sensible.

**Comment by trickeydan** [comment]
> Considering this is only planned to be installed on the two backup servers, I'm not convinced it's worthwhile packaging it, particularly as it would be a bunch of effort building a proper repo and maintaining the dependencies?
> 
> If we end up writing python stuff that we deploy to all servers though, I think properly packaging that would be sensible.

Packaging python into debs is very easy. https://fpm.readthedocs.io/en/latest/
